#include <stdio.h>
#include <assert.h>
#include <math.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


int sum_of_even_fibonacci_numbers_below(int n) {
    
    int x = 1;
    int y = 2;
    int fib = 0;

    int total = 2;

    while (fib < n) {
        fib = x + y;
        x = y;
        y = fib;
        if (fib % 2 == 0) {
            total += fib;
        }
    }

    return total;
}

int main() {
    int x = sum_of_even_fibonacci_numbers_below(10);
    printf("%d", x);
        assert(x == 10);
    int million = pow(10,4);
    int y = sum_of_even_fibonacci_numbers_below(4 * million);
    printf("The sumer of even fibonacci numbers below 400 is: %d", y);
}